# coding: utf-8

"""
    VoltSnip HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from voltsnip_client.models.snippet_kind import SnippetKind
from typing import Optional, Set
from typing_extensions import Self

class SnippetDetailResponse(BaseModel):
    """
    SnippetDetailResponse
    """ # noqa: E501
    title: Optional[Annotated[str, Field(strict=True, max_length=200)]] = None
    description: Optional[Annotated[str, Field(strict=True, max_length=1000)]] = None
    language: Optional[Annotated[str, Field(strict=True, max_length=50)]] = None
    tags: Optional[List[Annotated[str, Field(strict=True, max_length=50)]]] = Field(default=None, description="List of normalized tags associated with this snippet")
    kind: Optional[SnippetKind] = Field(default=None, description="The type of snippet (e.g., snippet, skill, prompt, utility, config)")
    canonical_key: Optional[Annotated[str, Field(strict=True, max_length=200)]] = None
    id: UUID
    created_at: datetime
    updated_at: datetime
    expires_at: Optional[datetime] = None
    view_count: Optional[StrictInt] = 0
    upvote_count: Optional[StrictInt] = 0
    downvote_count: Optional[StrictInt] = 0
    reference_count: Optional[StrictInt] = 0
    status: Optional[StrictStr] = 'active'
    highlighted_url: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=2083)]] = None
    is_hidden: Optional[StrictBool] = False
    hidden_reason: Optional[StrictStr] = None
    source: Optional[StrictStr] = 'human'
    blob_key: StrictStr
    code: StrictStr
    __properties: ClassVar[List[str]] = ["title", "description", "language", "tags", "kind", "canonical_key", "id", "created_at", "updated_at", "expires_at", "view_count", "upvote_count", "downvote_count", "reference_count", "status", "highlighted_url", "is_hidden", "hidden_reason", "source", "blob_key", "code"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['active', 'expired', 'survived']):
            raise ValueError("must be one of enum values ('active', 'expired', 'survived')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SnippetDetailResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if canonical_key (nullable) is None
        # and model_fields_set contains the field
        if self.canonical_key is None and "canonical_key" in self.model_fields_set:
            _dict['canonical_key'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expires_at'] = None

        # set to None if highlighted_url (nullable) is None
        # and model_fields_set contains the field
        if self.highlighted_url is None and "highlighted_url" in self.model_fields_set:
            _dict['highlighted_url'] = None

        # set to None if hidden_reason (nullable) is None
        # and model_fields_set contains the field
        if self.hidden_reason is None and "hidden_reason" in self.model_fields_set:
            _dict['hidden_reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SnippetDetailResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "description": obj.get("description"),
            "language": obj.get("language"),
            "tags": obj.get("tags"),
            "kind": obj.get("kind"),
            "canonical_key": obj.get("canonical_key"),
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "expires_at": obj.get("expires_at"),
            "view_count": obj.get("view_count") if obj.get("view_count") is not None else 0,
            "upvote_count": obj.get("upvote_count") if obj.get("upvote_count") is not None else 0,
            "downvote_count": obj.get("downvote_count") if obj.get("downvote_count") is not None else 0,
            "reference_count": obj.get("reference_count") if obj.get("reference_count") is not None else 0,
            "status": obj.get("status") if obj.get("status") is not None else 'active',
            "highlighted_url": obj.get("highlighted_url"),
            "is_hidden": obj.get("is_hidden") if obj.get("is_hidden") is not None else False,
            "hidden_reason": obj.get("hidden_reason"),
            "source": obj.get("source") if obj.get("source") is not None else 'human',
            "blob_key": obj.get("blob_key"),
            "code": obj.get("code")
        })
        return _obj


