# coding: utf-8

"""
    VoltSnip HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from voltsnip_client.models.snippet_kind import SnippetKind
from typing import Optional, Set
from typing_extensions import Self

class SnippetCreate(BaseModel):
    """
    SnippetCreate
    """ # noqa: E501
    title: Optional[Annotated[str, Field(strict=True, max_length=200)]] = None
    description: Optional[Annotated[str, Field(strict=True, max_length=1000)]] = None
    language: Optional[Annotated[str, Field(strict=True, max_length=50)]] = None
    tags: Optional[List[Annotated[str, Field(strict=True, max_length=50)]]] = Field(default=None, description="List of normalized tags associated with this snippet")
    kind: Optional[SnippetKind] = Field(default=None, description="The type of snippet (e.g., snippet, skill, prompt, utility, config)")
    canonical_key: Optional[Annotated[str, Field(strict=True, max_length=200)]] = None
    code: Annotated[str, Field(strict=True, max_length=1000000)] = Field(description="The actual code or text content")
    source: Optional[StrictStr] = None
    parent_id: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["title", "description", "language", "tags", "kind", "canonical_key", "code", "source", "parent_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SnippetCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if canonical_key (nullable) is None
        # and model_fields_set contains the field
        if self.canonical_key is None and "canonical_key" in self.model_fields_set:
            _dict['canonical_key'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['source'] = None

        # set to None if parent_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_id is None and "parent_id" in self.model_fields_set:
            _dict['parent_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SnippetCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "description": obj.get("description"),
            "language": obj.get("language"),
            "tags": obj.get("tags"),
            "kind": obj.get("kind"),
            "canonical_key": obj.get("canonical_key"),
            "code": obj.get("code"),
            "source": obj.get("source"),
            "parent_id": obj.get("parent_id")
        })
        return _obj


