DEFAULT_TIMEOUT_SECONDS = 1.5
DEFAULT_MAX_RETRY_ATTEMPTS = 3
DEFAULT_BACKOFF_SECONDS = 0.1
DEFAULT_JITTER_SECONDS = 0.05

DEFAULT_RETRYABLE_STATUS_CODES = {404, 408, 429, 500, 502, 503, 504}  # BUG_01: includes non-retryable 4xx (404).
DEFAULT_IDEMPOTENT_METHODS = {"GET", "HEAD", "PUT", "DELETE", "OPTIONS"}

LOG_REQUEST_ID_FIELD = "request_id"
SENSITIVE_FIELD_NAMES = {"password", "token", "api_key", "authorization", "secret"}
