# coding: utf-8

"""
    VoltSnip HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voltsnip_client.models.snippet_create import SnippetCreate

class TestSnippetCreate(unittest.TestCase):
    """SnippetCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SnippetCreate:
        """Test SnippetCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SnippetCreate`
        """
        model = SnippetCreate()
        if include_optional:
            return SnippetCreate(
                title = '',
                description = '',
                language = '',
                tags = [
                    ''
                    ],
                kind = 'snippet',
                canonical_key = '',
                code = '',
                source = '',
                parent_id = ''
            )
        else:
            return SnippetCreate(
                code = '',
        )
        """

    def testSnippetCreate(self):
        """Test SnippetCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
