# coding: utf-8

"""
    VoltSnip HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voltsnip_client.api.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchApi()

    def tearDown(self) -> None:
        pass

    def test_search_api_v1_search_get(self) -> None:
        """Test case for search_api_v1_search_get

        Search
        """
        pass

    def test_semantic_search_api_v1_search_semantic_get(self) -> None:
        """Test case for semantic_search_api_v1_search_semantic_get

        Semantic Search
        """
        pass


if __name__ == '__main__':
    unittest.main()
