# coding: utf-8

"""
    VoltSnip HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voltsnip_client.models.snippet_kind import SnippetKind

class TestSnippetKind(unittest.TestCase):
    """SnippetKind unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnippetKind(self):
        """Test SnippetKind"""
        # inst = SnippetKind()

if __name__ == '__main__':
    unittest.main()
