# coding: utf-8

"""
    VoltSnip HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voltsnip_client.models.snippet_meta_response import SnippetMetaResponse

class TestSnippetMetaResponse(unittest.TestCase):
    """SnippetMetaResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SnippetMetaResponse:
        """Test SnippetMetaResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SnippetMetaResponse`
        """
        model = SnippetMetaResponse()
        if include_optional:
            return SnippetMetaResponse(
                title = '',
                description = '',
                language = '',
                tags = [
                    ''
                    ],
                kind = 'snippet',
                canonical_key = '',
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                view_count = 56,
                upvote_count = 56,
                downvote_count = 56,
                reference_count = 56,
                status = 'active',
                highlighted_url = '0',
                is_hidden = True,
                hidden_reason = '',
                source = 'human'
            )
        else:
            return SnippetMetaResponse(
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testSnippetMetaResponse(self):
        """Test SnippetMetaResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
