# coding: utf-8

"""
    VoltSnip HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voltsnip_client.api.snippets_api import SnippetsApi


class TestSnippetsApi(unittest.TestCase):
    """SnippetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SnippetsApi()

    def tearDown(self) -> None:
        pass

    def test_create_snippet_api_v1_snippets_post(self) -> None:
        """Test case for create_snippet_api_v1_snippets_post

        Create Snippet
        """
        pass

    def test_read_snippet_api_v1_snippets_snippet_id_get(self) -> None:
        """Test case for read_snippet_api_v1_snippets_snippet_id_get

        Read Snippet
        """
        pass

    def test_read_snippet_by_canonical_key_api_v1_snippets_by_key_canonical_key_get(self) -> None:
        """Test case for read_snippet_by_canonical_key_api_v1_snippets_by_key_canonical_key_get

        Read Snippet By Canonical Key
        """
        pass

    def test_view_snippet_api_v1_snippets_snippet_id_view_post(self) -> None:
        """Test case for view_snippet_api_v1_snippets_snippet_id_view_post

        View Snippet
        """
        pass

    def test_vote_snippet_api_v1_snippets_snippet_id_vote_post(self) -> None:
        """Test case for vote_snippet_api_v1_snippets_snippet_id_vote_post

        Vote Snippet
        """
        pass


if __name__ == '__main__':
    unittest.main()
