# coding: utf-8

"""
    VoltSnip HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voltsnip_client.api.feeds_api import FeedsApi


class TestFeedsApi(unittest.TestCase):
    """FeedsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeedsApi()

    def tearDown(self) -> None:
        pass

    def test_hot_feed_api_v1_feeds_hot_get(self) -> None:
        """Test case for hot_feed_api_v1_feeds_hot_get

        Hot Feed
        """
        pass

    def test_most_used_feed_api_v1_feeds_most_used_get(self) -> None:
        """Test case for most_used_feed_api_v1_feeds_most_used_get

        Most Used Feed
        """
        pass

    def test_top_feed_api_v1_feeds_top_get(self) -> None:
        """Test case for top_feed_api_v1_feeds_top_get

        Top Feed
        """
        pass

    def test_trending_feed_api_v1_feeds_trending_get(self) -> None:
        """Test case for trending_feed_api_v1_feeds_trending_get

        Trending Feed
        """
        pass


if __name__ == '__main__':
    unittest.main()
