/* tslint:disable */
/* eslint-disable */
/**
 * VoltSnip HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SnippetKind } from './SnippetKind';
import {
    SnippetKindFromJSON,
    SnippetKindFromJSONTyped,
    SnippetKindToJSON,
    SnippetKindToJSONTyped,
} from './SnippetKind';

/**
 * 
 * @export
 * @interface SnippetCreate
 */
export interface SnippetCreate {
    /**
     * 
     * @type {string}
     * @memberof SnippetCreate
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnippetCreate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnippetCreate
     */
    language?: string | null;
    /**
     * List of normalized tags associated with this snippet
     * @type {Array<string>}
     * @memberof SnippetCreate
     */
    tags?: Array<string>;
    /**
     * The type of snippet (e.g., snippet, skill, prompt, utility, config)
     * @type {SnippetKind}
     * @memberof SnippetCreate
     */
    kind?: SnippetKind;
    /**
     * 
     * @type {string}
     * @memberof SnippetCreate
     */
    canonicalKey?: string | null;
    /**
     * The actual code or text content
     * @type {string}
     * @memberof SnippetCreate
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof SnippetCreate
     */
    source?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnippetCreate
     */
    parentId?: string | null;
}



/**
 * Check if a given object implements the SnippetCreate interface.
 */
export function instanceOfSnippetCreate(value: object): value is SnippetCreate {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function SnippetCreateFromJSON(json: any): SnippetCreate {
    return SnippetCreateFromJSONTyped(json, false);
}

export function SnippetCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnippetCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'language': json['language'] == null ? undefined : json['language'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'kind': json['kind'] == null ? undefined : SnippetKindFromJSON(json['kind']),
        'canonicalKey': json['canonical_key'] == null ? undefined : json['canonical_key'],
        'code': json['code'],
        'source': json['source'] == null ? undefined : json['source'],
        'parentId': json['parent_id'] == null ? undefined : json['parent_id'],
    };
}

export function SnippetCreateToJSON(json: any): SnippetCreate {
    return SnippetCreateToJSONTyped(json, false);
}

export function SnippetCreateToJSONTyped(value?: SnippetCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'language': value['language'],
        'tags': value['tags'],
        'kind': SnippetKindToJSON(value['kind']),
        'canonical_key': value['canonicalKey'],
        'code': value['code'],
        'source': value['source'],
        'parent_id': value['parentId'],
    };
}

