/* tslint:disable */
/* eslint-disable */
/**
 * VoltSnip HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SnippetKind } from './SnippetKind';
import {
    SnippetKindFromJSON,
    SnippetKindFromJSONTyped,
    SnippetKindToJSON,
    SnippetKindToJSONTyped,
} from './SnippetKind';

/**
 * 
 * @export
 * @interface SnippetDetailResponse
 */
export interface SnippetDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof SnippetDetailResponse
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnippetDetailResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnippetDetailResponse
     */
    language?: string | null;
    /**
     * List of normalized tags associated with this snippet
     * @type {Array<string>}
     * @memberof SnippetDetailResponse
     */
    tags?: Array<string>;
    /**
     * The type of snippet (e.g., snippet, skill, prompt, utility, config)
     * @type {SnippetKind}
     * @memberof SnippetDetailResponse
     */
    kind?: SnippetKind;
    /**
     * 
     * @type {string}
     * @memberof SnippetDetailResponse
     */
    canonicalKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnippetDetailResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof SnippetDetailResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SnippetDetailResponse
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SnippetDetailResponse
     */
    expiresAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof SnippetDetailResponse
     */
    viewCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SnippetDetailResponse
     */
    upvoteCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SnippetDetailResponse
     */
    downvoteCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SnippetDetailResponse
     */
    referenceCount?: number;
    /**
     * 
     * @type {string}
     * @memberof SnippetDetailResponse
     */
    status?: SnippetDetailResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof SnippetDetailResponse
     */
    highlightedUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SnippetDetailResponse
     */
    isHidden?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SnippetDetailResponse
     */
    hiddenReason?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SnippetDetailResponse
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof SnippetDetailResponse
     */
    blobKey: string;
    /**
     * 
     * @type {string}
     * @memberof SnippetDetailResponse
     */
    code: string;
}


/**
 * @export
 */
export const SnippetDetailResponseStatusEnum = {
    Active: 'active',
    Expired: 'expired',
    Survived: 'survived'
} as const;
export type SnippetDetailResponseStatusEnum = typeof SnippetDetailResponseStatusEnum[keyof typeof SnippetDetailResponseStatusEnum];


/**
 * Check if a given object implements the SnippetDetailResponse interface.
 */
export function instanceOfSnippetDetailResponse(value: object): value is SnippetDetailResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('blobKey' in value) || value['blobKey'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function SnippetDetailResponseFromJSON(json: any): SnippetDetailResponse {
    return SnippetDetailResponseFromJSONTyped(json, false);
}

export function SnippetDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnippetDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'language': json['language'] == null ? undefined : json['language'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'kind': json['kind'] == null ? undefined : SnippetKindFromJSON(json['kind']),
        'canonicalKey': json['canonical_key'] == null ? undefined : json['canonical_key'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'viewCount': json['view_count'] == null ? undefined : json['view_count'],
        'upvoteCount': json['upvote_count'] == null ? undefined : json['upvote_count'],
        'downvoteCount': json['downvote_count'] == null ? undefined : json['downvote_count'],
        'referenceCount': json['reference_count'] == null ? undefined : json['reference_count'],
        'status': json['status'] == null ? undefined : json['status'],
        'highlightedUrl': json['highlighted_url'] == null ? undefined : json['highlighted_url'],
        'isHidden': json['is_hidden'] == null ? undefined : json['is_hidden'],
        'hiddenReason': json['hidden_reason'] == null ? undefined : json['hidden_reason'],
        'source': json['source'] == null ? undefined : json['source'],
        'blobKey': json['blob_key'],
        'code': json['code'],
    };
}

export function SnippetDetailResponseToJSON(json: any): SnippetDetailResponse {
    return SnippetDetailResponseToJSONTyped(json, false);
}

export function SnippetDetailResponseToJSONTyped(value?: SnippetDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'language': value['language'],
        'tags': value['tags'],
        'kind': SnippetKindToJSON(value['kind']),
        'canonical_key': value['canonicalKey'],
        'id': value['id'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'view_count': value['viewCount'],
        'upvote_count': value['upvoteCount'],
        'downvote_count': value['downvoteCount'],
        'reference_count': value['referenceCount'],
        'status': value['status'],
        'highlighted_url': value['highlightedUrl'],
        'is_hidden': value['isHidden'],
        'hidden_reason': value['hiddenReason'],
        'source': value['source'],
        'blob_key': value['blobKey'],
        'code': value['code'],
    };
}

