/* tslint:disable */
/* eslint-disable */
/**
 * VoltSnip HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SnippetKind = {
    Snippet: 'snippet',
    Skill: 'skill',
    Prompt: 'prompt',
    Utility: 'utility',
    Config: 'config'
} as const;
export type SnippetKind = typeof SnippetKind[keyof typeof SnippetKind];


export function instanceOfSnippetKind(value: any): boolean {
    for (const key in SnippetKind) {
        if (Object.prototype.hasOwnProperty.call(SnippetKind, key)) {
            if (SnippetKind[key as keyof typeof SnippetKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SnippetKindFromJSON(json: any): SnippetKind {
    return SnippetKindFromJSONTyped(json, false);
}

export function SnippetKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnippetKind {
    return json as SnippetKind;
}

export function SnippetKindToJSON(value?: SnippetKind | null): any {
    return value as any;
}

export function SnippetKindToJSONTyped(value: any, ignoreDiscriminator: boolean): SnippetKind {
    return value as SnippetKind;
}

