/* tslint:disable */
/* eslint-disable */
/**
 * VoltSnip HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Vote
 */
export interface Vote {
    /**
     * 
     * @type {number}
     * @memberof Vote
     */
    value: VoteValueEnum;
}


/**
 * @export
 */
export const VoteValueEnum = {
    NUMBER_MINUS_1: -1,
    NUMBER_1: 1
} as const;
export type VoteValueEnum = typeof VoteValueEnum[keyof typeof VoteValueEnum];


/**
 * Check if a given object implements the Vote interface.
 */
export function instanceOfVote(value: object): value is Vote {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function VoteFromJSON(json: any): Vote {
    return VoteFromJSONTyped(json, false);
}

export function VoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Vote {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function VoteToJSON(json: any): Vote {
    return VoteToJSONTyped(json, false);
}

export function VoteToJSONTyped(value?: Vote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

