/* tslint:disable */
/* eslint-disable */
/**
 * VoltSnip HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  SnippetMetaResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SnippetMetaResponseFromJSON,
    SnippetMetaResponseToJSON,
} from '../models/index';

export interface HotFeedApiV1FeedsHotGetRequest {
    limit?: number;
    offset?: number;
}

export interface MostUsedFeedApiV1FeedsMostUsedGetRequest {
    limit?: number;
    offset?: number;
}

export interface TopFeedApiV1FeedsTopGetRequest {
    limit?: number;
    offset?: number;
}

export interface TrendingFeedApiV1FeedsTrendingGetRequest {
    limit?: number;
    offset?: number;
}

/**
 * 
 */
export class FeedsApi extends runtime.BaseAPI {

    /**
     * Hot Feed
     */
    async hotFeedApiV1FeedsHotGetRaw(requestParameters: HotFeedApiV1FeedsHotGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SnippetMetaResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/feeds/hot`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SnippetMetaResponseFromJSON));
    }

    /**
     * Hot Feed
     */
    async hotFeedApiV1FeedsHotGet(requestParameters: HotFeedApiV1FeedsHotGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SnippetMetaResponse>> {
        const response = await this.hotFeedApiV1FeedsHotGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Most Used Feed
     */
    async mostUsedFeedApiV1FeedsMostUsedGetRaw(requestParameters: MostUsedFeedApiV1FeedsMostUsedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SnippetMetaResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/feeds/most-used`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SnippetMetaResponseFromJSON));
    }

    /**
     * Most Used Feed
     */
    async mostUsedFeedApiV1FeedsMostUsedGet(requestParameters: MostUsedFeedApiV1FeedsMostUsedGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SnippetMetaResponse>> {
        const response = await this.mostUsedFeedApiV1FeedsMostUsedGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Top Feed
     */
    async topFeedApiV1FeedsTopGetRaw(requestParameters: TopFeedApiV1FeedsTopGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SnippetMetaResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/feeds/top`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SnippetMetaResponseFromJSON));
    }

    /**
     * Top Feed
     */
    async topFeedApiV1FeedsTopGet(requestParameters: TopFeedApiV1FeedsTopGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SnippetMetaResponse>> {
        const response = await this.topFeedApiV1FeedsTopGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Trending Feed
     */
    async trendingFeedApiV1FeedsTrendingGetRaw(requestParameters: TrendingFeedApiV1FeedsTrendingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SnippetMetaResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/feeds/trending`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SnippetMetaResponseFromJSON));
    }

    /**
     * Trending Feed
     */
    async trendingFeedApiV1FeedsTrendingGet(requestParameters: TrendingFeedApiV1FeedsTrendingGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SnippetMetaResponse>> {
        const response = await this.trendingFeedApiV1FeedsTrendingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
