/* tslint:disable */
/* eslint-disable */
/**
 * VoltSnip HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  SnippetMetaResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SnippetMetaResponseFromJSON,
    SnippetMetaResponseToJSON,
} from '../models/index';

export interface SearchApiV1SearchGetRequest {
    tag?: string | null;
    language?: string | null;
    title?: string | null;
    limit?: number;
    offset?: number;
}

export interface SemanticSearchApiV1SearchSemanticGetRequest {
    q: string;
    k?: number;
}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI {

    /**
     * Search
     */
    async searchApiV1SearchGetRaw(requestParameters: SearchApiV1SearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SnippetMetaResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['tag'] != null) {
            queryParameters['tag'] = requestParameters['tag'];
        }

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        if (requestParameters['title'] != null) {
            queryParameters['title'] = requestParameters['title'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/search/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SnippetMetaResponseFromJSON));
    }

    /**
     * Search
     */
    async searchApiV1SearchGet(requestParameters: SearchApiV1SearchGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SnippetMetaResponse>> {
        const response = await this.searchApiV1SearchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Semantic Search
     */
    async semanticSearchApiV1SearchSemanticGetRaw(requestParameters: SemanticSearchApiV1SearchSemanticGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SnippetMetaResponse>>> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling semanticSearchApiV1SearchSemanticGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['k'] != null) {
            queryParameters['k'] = requestParameters['k'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/search/semantic`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SnippetMetaResponseFromJSON));
    }

    /**
     * Semantic Search
     */
    async semanticSearchApiV1SearchSemanticGet(requestParameters: SemanticSearchApiV1SearchSemanticGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SnippetMetaResponse>> {
        const response = await this.semanticSearchApiV1SearchSemanticGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
