/* tslint:disable */
/* eslint-disable */
/**
 * VoltSnip HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  SnippetCreate,
  SnippetDetailResponse,
  SnippetMetaResponse,
  Vote,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SnippetCreateFromJSON,
    SnippetCreateToJSON,
    SnippetDetailResponseFromJSON,
    SnippetDetailResponseToJSON,
    SnippetMetaResponseFromJSON,
    SnippetMetaResponseToJSON,
    VoteFromJSON,
    VoteToJSON,
} from '../models/index';

export interface CreateSnippetApiV1SnippetsPostRequest {
    snippetCreate: SnippetCreate;
}

export interface ReadSnippetApiV1SnippetsSnippetIdGetRequest {
    snippetId: string;
}

export interface ViewSnippetApiV1SnippetsSnippetIdViewPostRequest {
    snippetId: string;
}

export interface VoteSnippetApiV1SnippetsSnippetIdVotePostRequest {
    snippetId: string;
    vote: Vote;
}

/**
 * 
 */
export class SnippetsApi extends runtime.BaseAPI {

    /**
     * Create Snippet
     */
    async createSnippetApiV1SnippetsPostRaw(requestParameters: CreateSnippetApiV1SnippetsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SnippetDetailResponse>> {
        if (requestParameters['snippetCreate'] == null) {
            throw new runtime.RequiredError(
                'snippetCreate',
                'Required parameter "snippetCreate" was null or undefined when calling createSnippetApiV1SnippetsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/snippets/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SnippetCreateToJSON(requestParameters['snippetCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SnippetDetailResponseFromJSON(jsonValue));
    }

    /**
     * Create Snippet
     */
    async createSnippetApiV1SnippetsPost(requestParameters: CreateSnippetApiV1SnippetsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SnippetDetailResponse> {
        const response = await this.createSnippetApiV1SnippetsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Read Snippet
     */
    async readSnippetApiV1SnippetsSnippetIdGetRaw(requestParameters: ReadSnippetApiV1SnippetsSnippetIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SnippetDetailResponse>> {
        if (requestParameters['snippetId'] == null) {
            throw new runtime.RequiredError(
                'snippetId',
                'Required parameter "snippetId" was null or undefined when calling readSnippetApiV1SnippetsSnippetIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/snippets/{snippet_id}`;
        urlPath = urlPath.replace(`{${"snippet_id"}}`, encodeURIComponent(String(requestParameters['snippetId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SnippetDetailResponseFromJSON(jsonValue));
    }

    /**
     * Read Snippet
     */
    async readSnippetApiV1SnippetsSnippetIdGet(requestParameters: ReadSnippetApiV1SnippetsSnippetIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SnippetDetailResponse> {
        const response = await this.readSnippetApiV1SnippetsSnippetIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * View Snippet
     */
    async viewSnippetApiV1SnippetsSnippetIdViewPostRaw(requestParameters: ViewSnippetApiV1SnippetsSnippetIdViewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SnippetMetaResponse>> {
        if (requestParameters['snippetId'] == null) {
            throw new runtime.RequiredError(
                'snippetId',
                'Required parameter "snippetId" was null or undefined when calling viewSnippetApiV1SnippetsSnippetIdViewPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/snippets/{snippet_id}/view`;
        urlPath = urlPath.replace(`{${"snippet_id"}}`, encodeURIComponent(String(requestParameters['snippetId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SnippetMetaResponseFromJSON(jsonValue));
    }

    /**
     * View Snippet
     */
    async viewSnippetApiV1SnippetsSnippetIdViewPost(requestParameters: ViewSnippetApiV1SnippetsSnippetIdViewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SnippetMetaResponse> {
        const response = await this.viewSnippetApiV1SnippetsSnippetIdViewPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Vote Snippet
     */
    async voteSnippetApiV1SnippetsSnippetIdVotePostRaw(requestParameters: VoteSnippetApiV1SnippetsSnippetIdVotePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SnippetMetaResponse>> {
        if (requestParameters['snippetId'] == null) {
            throw new runtime.RequiredError(
                'snippetId',
                'Required parameter "snippetId" was null or undefined when calling voteSnippetApiV1SnippetsSnippetIdVotePost().'
            );
        }

        if (requestParameters['vote'] == null) {
            throw new runtime.RequiredError(
                'vote',
                'Required parameter "vote" was null or undefined when calling voteSnippetApiV1SnippetsSnippetIdVotePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/snippets/{snippet_id}/vote`;
        urlPath = urlPath.replace(`{${"snippet_id"}}`, encodeURIComponent(String(requestParameters['snippetId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VoteToJSON(requestParameters['vote']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SnippetMetaResponseFromJSON(jsonValue));
    }

    /**
     * Vote Snippet
     */
    async voteSnippetApiV1SnippetsSnippetIdVotePost(requestParameters: VoteSnippetApiV1SnippetsSnippetIdVotePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SnippetMetaResponse> {
        const response = await this.voteSnippetApiV1SnippetsSnippetIdVotePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
